package webservice.client.jaxwsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "qqOnlineWebServiceHttpPost", targetNamespace = "http://WebXml.com.cn/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QqOnlineWebServiceHttpPost {

	/**
	 * <br />
	 * <h3>�����ѶQQ����״̬</h3>
	 * <p>
	 * �������QQ���� String��Ĭ��QQ���룺8698053��������ݣ�String��Y = ���ߣ�N =
	 * ���ߣ�E = QQ�������A = ��ҵ�û���֤ʧ�ܣ�V = ����û�������
	 * </p>
	 * <br />
	 * 
	 * @param qqCode
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "string", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
	public String qqCheckOnline(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "qqCode")
			String qqCode);

}
