package webservice.client.jaxwsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a>
 * <strong>��ѶQQ����״̬ WEB ����</strong>��<a href="http://www.webxml.com.cn/"
 * target="_blank">WebXml.com.cn</a>
 * ��/�����Ӧ�̲�Ϊ��ҳ���ṩ��Ϣ�Ĵ��󡢲�ȱ���ӳٻ����?�����Ϣ���ȡ���κ��ж�����</br>����ѶQQ����״̬Web
 * Services�벻Ҫ�����κ���ҵĿ�ģ�������Ҫ��<a
 * href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">jϵ����</a>����ӭ������
 * QQ��8409035<br />
 * <strong>ʹ�ñ�վ WEB ������ע���t�ӱ�վ��http://www.webxml.com.cn/ ��л��ҵ�֧��</strong>��<br />
 * <br />
 * &nbsp;
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * qqOnlineWebService service = new qqOnlineWebService();
 * QqOnlineWebServiceSoap portType = service.getQqOnlineWebServiceSoap();
 * portType.qqCheckOnline(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "qqOnlineWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx?wsdl")
public class QqOnlineWebService extends Service {

	private final static URL QQONLINEWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(webservice.client.jaxwsclient.QqOnlineWebService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webservice.client.jaxwsclient.QqOnlineWebService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		QQONLINEWEBSERVICE_WSDL_LOCATION = url;
	}

	public QqOnlineWebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public QqOnlineWebService() {
		super(QQONLINEWEBSERVICE_WSDL_LOCATION, new QName(
				"http://WebXml.com.cn/", "qqOnlineWebService"));
	}

	/**
	 * 
	 * @return returns QqOnlineWebServiceSoap
	 */
	@WebEndpoint(name = "qqOnlineWebServiceSoap")
	public QqOnlineWebServiceSoap getQqOnlineWebServiceSoap() {
		return super.getPort(new QName("http://WebXml.com.cn/",
				"qqOnlineWebServiceSoap"), QqOnlineWebServiceSoap.class);
	}

	/**
	 * 
	 * @return returns QqOnlineWebServiceSoap
	 */
	@WebEndpoint(name = "qqOnlineWebServiceSoap12")
	public QqOnlineWebServiceSoap getQqOnlineWebServiceSoap12() {
		return super.getPort(new QName("http://WebXml.com.cn/",
				"qqOnlineWebServiceSoap12"), QqOnlineWebServiceSoap.class);
	}

	/**
	 * 
	 * @return returns QqOnlineWebServiceHttpGet
	 */
	@WebEndpoint(name = "qqOnlineWebServiceHttpGet")
	public QqOnlineWebServiceHttpGet getQqOnlineWebServiceHttpGet() {
		return super.getPort(new QName("http://WebXml.com.cn/",
				"qqOnlineWebServiceHttpGet"), QqOnlineWebServiceHttpGet.class);
	}

	/**
	 * 
	 * @return returns QqOnlineWebServiceHttpPost
	 */
	@WebEndpoint(name = "qqOnlineWebServiceHttpPost")
	public QqOnlineWebServiceHttpPost getQqOnlineWebServiceHttpPost() {
		return super
				.getPort(new QName("http://WebXml.com.cn/",
						"qqOnlineWebServiceHttpPost"),
						QqOnlineWebServiceHttpPost.class);
	}

}
