package webservice.client.jaxwsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "qqOnlineWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
public interface QqOnlineWebServiceSoap {

	/**
	 * @param qqCode
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://WebXml.com.cn/qqCheckOnline")
	@WebResult(name = "qqCheckOnlineResult", targetNamespace = "http://WebXml.com.cn/")
	@RequestWrapper(localName = "qqCheckOnline", targetNamespace = "http://WebXml.com.cn/", className = "webservice.client.jaxwsclient.QqCheckOnline")
	@ResponseWrapper(localName = "qqCheckOnlineResponse", targetNamespace = "http://WebXml.com.cn/", className = "webservice.client.jaxwsclient.QqCheckOnlineResponse")
	public String qqCheckOnline(
			@WebParam(name = "qqCode", targetNamespace = "http://WebXml.com.cn/")
			String qqCode
			);

}
